apiVersion: v1
kind: Namespace
metadata:
  name: dailycs

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dailycs-question-generate
  namespace: dailycs
spec:
  schedule: "0 * * * *"  # 매 시간 0분마다 -> gemini 2.5 pro : 25 req per day
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: dailycs-question-generator
            image: omoknooni/dailycs-question-generator:latest
            envFrom:
            - secretRef:
                name: aws-creds
            - secretRef:
                name: chromadb
          restartPolicy: Never